"""empty message

Revision ID: 57994f8ea9c4
Revises: fab9f6215491
Create Date: 2021-04-17 16:19:21.048233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57994f8ea9c4'
down_revision = 'fab9f6215491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'points')
    # ### end Alembic commands ###
