"""empty message

Revision ID: b64f65438ec3
Revises: 846046050d25
Create Date: 2021-04-22 00:09:31.390103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64f65438ec3'
down_revision = '846046050d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('upgrade_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'upgrade_time')
    # ### end Alembic commands ###
