"""empty message

Revision ID: fab9f6215491
Revises: bbc5b5cfbdee
Create Date: 2021-04-17 15:58:39.547039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab9f6215491'
down_revision = 'bbc5b5cfbdee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('q_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'q_level')
    # ### end Alembic commands ###
